### ISSUE TITLE
hw95 feedback

### ISSUE THREAD

**Issue by MKendall17** [Rachel-W3/WuWongClan_Wong-R_Wu-J#3]
So overall I am pretty happy with the descriptions.  Here are some more minor comments:  

### statement of problem  
Make sure that when you say designated beginning, you don't mean the first point where the explorer starts.  If it is that, then we can't apply the recursive abstraction.  
Also, the shortest possible path should probably be a later version idea.

### recursive abstraction
When you say "I ask the recursive abstraction to find a path...", to cover the case where a path does not exist, say that the recursive abstraction returns the boolean value that there exists a path from a neighboring spot to the treasure.

### base case
The "else" is a stretch -- it doesn't indicate whether the place you are on a point that has adjacent paths or not.  Change this else case to being in a wall.

### pseudocode
Expanding off from above, instead of looking at whether an adjacent step is a dead end, move to that step and invoke the base case (the else case).  
The last two lines should probably be on top of the if statement too: we first choose a turn to see whether it is a dead end or not.  Then we continue to do this.

Hopefully at least some parts of this are helpful to you.

**Comment by Rachel-W3** [comment]
Thanks Matthew,
I already made changes to the README regarding the "designated beginning" phrasing and the shortest possible path. The README in the repo of holding is not the updated version.
Also, your suggestion to put the last lines on top cleared up a huge problem we've been having regarding how we should interpret "moving forward," so thank you for that.
